import 'package:connector_openapi/api.dart';

final List<Map<String, dynamic>> programmingLanguages = [
{'ext': ClassificationSpecificEnum.bat, 'name': 'Batchfile'},
{'ext': ClassificationSpecificEnum.c, 'name': 'C'},
{'ext': ClassificationSpecificEnum.hljsClojure, 'name': 'Clojure'},
{'ext': ClassificationSpecificEnum.cs, 'name': 'C#'},
{'ext': ClassificationSpecificEnum.cs, 'name': 'Coffeescript'},
{'ext': ClassificationSpecificEnum.cpp, 'name': 'C++'},
{'ext': ClassificationSpecificEnum.css, 'name': 'CSS'},
{'ext': ClassificationSpecificEnum.dart, 'name': 'Dart'},
{'ext': ClassificationSpecificEnum.erl, 'name': 'Erlang'},
{'ext': ClassificationSpecificEnum.hljsLisp, 'name': 'Emacs Lisp'},
{'ext': ClassificationSpecificEnum.hljsElixir, 'name': 'Elixir'},
{'ext': ClassificationSpecificEnum.go, 'name': 'Go'},
{'ext': ClassificationSpecificEnum.hljsGroovy, 'name': 'Groovy'},
{'ext': ClassificationSpecificEnum.hs, 'name': 'Haskell'},
{'ext': ClassificationSpecificEnum.html, 'name': 'HTML'},
{'ext': ClassificationSpecificEnum.java, 'name': 'Java'},
{'ext': ClassificationSpecificEnum.js, 'name': 'Javascript'},
{'ext': ClassificationSpecificEnum.json, 'name': 'JSON'},
{'ext': ClassificationSpecificEnum.hljsKotlin, 'name': 'Kotlin'},
{'ext': ClassificationSpecificEnum.lua, 'name': 'Lua'},
{'ext': ClassificationSpecificEnum.md, 'name': 'MarkDown'},
{'ext': ClassificationSpecificEnum.matlab, 'name': 'Matlab'},
{'ext': ClassificationSpecificEnum.m, 'name': 'ObjectiveC'},
{'ext': ClassificationSpecificEnum.p, 'name': 'Perl'},
{'ext': ClassificationSpecificEnum.php, 'name': 'PHP'},
{'ext': ClassificationSpecificEnum.ps1, 'name': 'Powershell'},
{'ext': ClassificationSpecificEnum.py, 'name': 'Python'},
{'ext': ClassificationSpecificEnum.r, 'name': 'R'},
{'ext': ClassificationSpecificEnum.rb, 'name': 'Ruby'},
{'ext': ClassificationSpecificEnum.rs, 'name': 'Rust'},
{'ext': ClassificationSpecificEnum.scala, 'name': 'Scala'},
{'ext': ClassificationSpecificEnum.sh, 'name': 'Shell'},
{'ext': ClassificationSpecificEnum.sql, 'name': 'SQL'},
{'ext': ClassificationSpecificEnum.swift, 'name': 'Swift'},
{'ext': ClassificationSpecificEnum.ts, 'name': 'Typescript'},
{'ext': ClassificationSpecificEnum.tex, 'name': 'Tex'},
  {'ext': ClassificationSpecificEnum.tex, 'name': 'Tex'},
  {'ext': ClassificationSpecificEnum.text, 'name': 'Text'},
  {'ext': ClassificationSpecificEnum.toml, 'name': 'Toml'},
  {'ext': ClassificationSpecificEnum.xml, 'name': 'XML'},
  {'ext': ClassificationSpecificEnum.yaml, 'name': 'YAML'},
];
